use autodelen;
source implementation.sql;
source templates.sql;
source random_addresses.sql;
source random_users.sql;
source random_cars.sql;
source random_reservations.sql;
source random_infosessions.sql;
source random_infosession_enrollees.sql;
