DROP DATABASE IF EXISTS autodelen;
CREATE DATABASE autodelen;
USE autodelen;
source implementation.sql;
source templates.sql;
source settings.sql;
source users.sql;
source userroles.sql;
source addresses.sql;
source infosessions.sql;
source cars.sql;
