INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("2189","Ville-en-Hesbaye");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("2476","Bonnyville");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("7600ON","Wichita");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("808066","Jolanda di Savoia");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("658380","Pisa");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("65087","Zweibrï¿½cken");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("2291MA","Pievepelago");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("3471","Mont-Sainte-Geneviï¿½ve");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("7915","Drayton Valley");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("1000FE","Mogi das Cruzes");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("P7R 9M7","Piracicaba");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("7642","Zignago");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("S5V 2X2","Surrey");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("61415","Casper");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("Y2X 7V0","Halesowen");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("698417","Vieux-Genappe");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("9010","Argyle");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("7905","Sahiwal");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("82701-962","Kingston");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("40205","Vigo");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("54028","Kapfenberg");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("96206","Greenlaw");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("31500","Zwickau");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("79991-279","Trieste");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("3279ZE","Castelbuono");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("77173-707","Sunderland");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("6470","Marseille");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("3843","Cerchio");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("51618","Oudekapelle");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("56637","Ingooigem");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("60713","Wekweti");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("321535","Saint-Pierre");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("Q6L 5VQ","AÃ§ailÃ¢ndia");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("8691DR","Baden-Baden");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("62869","Sant'Angelo Limosano");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("41530","Wakefield");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("98988","Mal");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("29033","Lapscheure");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("4200","Farrukhabad-cum-Fatehgarh");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("53138","Rutten");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("8003NR","Bonavista");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("65952","Srinagar");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("68268","Banchory");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("36647","Hennigsdorf");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("94631","Gosselies");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("69742","Redwater");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("78369","Wyoming");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("2058AV","Rio nell'Elba");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("03072-851","Stekene");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("2692","Thorn");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("5307","Hearst");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("HC9H 1TM","Zelzate");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("7465","Hervey Bay");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("743272","Montecarotto");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("C8 9LM","Gols");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("B62 6JF","Driekapellen");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("8353","Hastings");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("R8S 0T1","Wortel");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("79227","Timon");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("83714","Hull");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("9278DS","Proddatur");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("72628","Machynlleth");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("1883","Tracadie-Shelia");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("129866","MÃ©rignac");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("C0P 0J7","Martelange");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("4149","Stornaway");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("4526","Lerwick");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("L1V 1T7","Baracaldo");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("25495","Meerdonk");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("80142","San Martino in Badia/St. Martin in Thurn");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("8756","Berlare");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("71329","Lower Hutt");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("9717","Zuienkerke");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("50301","Hildesheim");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("22915","Dï¿½sseldorf");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("426633","Shaftesbury");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("5131","Greenlaw");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("49709","Beverley");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("6578","Toledo");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("P2J 9T3","Huntley");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("H2A 8P7","San Mauro Cilento");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("10711","Sint-Michiels");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("71769","Oudenburg");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("59028-104","Port Alice");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("9669CP","Mores");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("Q2 8AP","Anzegem");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("SZ1 1MN","Elen");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("409108","Balurghat");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("0078","Bad Nauheim");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("V4K 2V0","Ospedaletto d'Alpinolo");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("8823MC","Oostkerke");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("K4A 9H9","Oostkerk");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("T9R 8C1","Crowsnest Pass");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("03012","Shipshaw");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("42639","Tramonti di Sopra");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("56394","Linton");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("2792BX","Comblain-la-Tour");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("78822","Leipzig");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("47268","Oordegem");
INSERT INTO `Places` (`place_zip`,`place_city`) VALUES ("8327","Mont");
