INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Tolentino","1602","6218 In St.",154,1);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Abergavenny","54350","P.O. Box 990, 2459 Nascetur Rd.",261,3);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Elmshorn","7287","P.O. Box 655, 7798 Nam Av.",275,8);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Crystal Springs","8774","3844 Vehicula St.",80,2);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Coaldale","4877FS","798-784 Nonummy St.",161,3);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Villers-la-Tour","3147","Ap #159-7487 Ornare, Av.",243,6);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Rycroft","1988","Ap #421-5852 Etiam Street",71,9);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Caccamo","25318","Ap #207-8260 Sed, Avenue",91,1);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Petrolina","40732","139-4777 Sagittis St.",10,3);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Warwick","6402","Ap #647-7981 Bibendum Ave",191,3);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Glossop","1869","P.O. Box 460, 6087 Ut Street",247,9);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Wood Buffalo","6254","P.O. Box 785, 1364 Quam. Rd.",83,2);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Meppel","8003","Ap #502-162 Arcu St.",133,10);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Carlton","88628","458 Pellentesque Ave",55,2);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Straubing","80634","668-2179 At St.",24,7);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Eschwege","2449","Ap #395-4727 Neque Av.",126,4);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("San Calogero","3948","492-2902 Posuere Street",291,7);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Rimbey","5169OD","P.O. Box 604, 7726 Pellentesque St.",187,8);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Duisburg","1597","1269 Porttitor Ave",250,4);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Castelluccio Valmaggiore","47983","P.O. Box 559, 2389 Lacinia Rd.",197,4);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Sherbrooke","245338","6755 Pellentesque Road",88,2);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Waalwijk","EI11 8GC","9122 Hendrerit Avenue",162,7);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Ribnitz-Damgarten","27527-733","Ap #638-9112 Diam St.",228,6);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Saguenay","55336","7788 Elementum Rd.",168,7);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("WÃ¶rgl","88966","P.O. Box 604, 816 Semper Rd.",57,10);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Merbes-Sainte-Marie","14303","8117 Libero. Street",51,4);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Hyderabad","47849","P.O. Box 654, 9349 Enim, Rd.",259,7);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Merbes-Sainte-Marie","72823","Ap #791-2194 Sociis St.",165,8);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Sirsa","7360","Ap #311-3080 Ipsum Avenue",161,1);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Jhang","651403","779-9143 Mauris Rd.",87,5);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Parramatta","OC6 5XO","P.O. Box 940, 7542 Orci. Rd.",131,3);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Ruda","9047","P.O. Box 506, 463 Ornare. Rd.",87,7);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Bregenz","60500","P.O. Box 915, 7697 Risus. Avenue",224,8);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Ciudad Real","22257","320-441 Mauris Avenue",147,6);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Salerno","00733","Ap #261-6644 Nec St.",277,3);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Pangnirtung","872628","2490 Luctus Rd.",121,9);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Heule","05681","Ap #313-4662 Pharetra. Street",77,4);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Fosses-la-Ville","31154","7227 Euismod Ave",18,10);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Margate","32727","P.O. Box 287, 5689 Sem Road",10,2);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Hattem","5205MT","P.O. Box 796, 2951 Justo. Road",95,6);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Nalinnes","88944-415","Ap #225-1845 Quis Rd.",52,1);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Etroubles","3332","P.O. Box 314, 6095 Enim. Ave",132,8);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("New Glasgow","15102","P.O. Box 201, 941 Nunc, Road",82,5);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Riviï¿½re","58456","P.O. Box 686, 7860 Sollicitudin St.",217,1);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Montegranaro","VZ0 3IP","630-5117 Morbi Street",183,7);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Zierikzee","28091","2492 Metus Road",268,3);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Fairbanks","118771","287-9953 Nec Rd.",114,2);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("San Gregorio nelle Alpi","4234","Ap #186-5718 Cubilia St.",152,2);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Sambhal","63149","P.O. Box 493, 4488 Mauris St.",255,1);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Filot","9611BU","P.O. Box 118, 5096 Commodo Rd.",150,6);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Oxford County","236824","Ap #113-2069 Justo Rd.",259,9);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Fernie","171751","7275 Enim Rd.",20,3);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Bayswater","26257","6670 Vitae St.",130,5);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Romford","27320","Ap #620-6686 Feugiat St.",85,6);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Prince Albert","J6 1YN","Ap #944-2187 Purus, St.",17,6);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Lacombe County","55797","Ap #332-8853 Molestie Street",8,4);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Sant'Agata Bolognese","7025","P.O. Box 257, 8418 Orci Avenue",29,2);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Hilo","2949","P.O. Box 458, 9120 Felis Street",211,5);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Florenville","2577","Ap #490-7885 Odio Road",167,7);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Guntakal","7008","145-2762 Vivamus Ave",112,10);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Dover","T5F 0VV","P.O. Box 350, 7879 Sed, Ave",21,9);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Meridian","2644TF","P.O. Box 270, 9578 Et Av.",218,3);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Bellegem","23850","Ap #517-6930 Lorem Rd.",148,5);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Tongerlo","10963","602-3121 Eu, St.",128,6);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Doetinchem","1092","Ap #118-6262 Egestas St.",68,9);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Musson","39733","536-209 Consequat Av.",270,8);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Warisoulx","8598","P.O. Box 845, 9589 Ac Rd.",229,7);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Granada","21113","911-4341 Arcu St.",227,8);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Sierning","1065","398-1957 Quam Ave",262,5);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Kerikeri","11585","Ap #713-5979 Arcu Ave",206,4);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Antwerpen","4566","408-1655 Nunc Ave",152,2);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Canora","19837","819-2332 Egestas. Road",297,6);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Calmar","24764","8004 Interdum Avenue",55,6);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Junagadh","77497-555","7560 Neque. Avenue",81,4);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Southwell","92554","5419 Lobortis, Rd.",138,2);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Vieux-Genappe","2748II","473-3995 Et, Street",146,6);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Ruette","MU8D 3DR","Ap #362-9705 Sed Av.",116,7);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Bikaner","126492","P.O. Box 889, 5846 Dui Street",33,4);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Bolzano Vicentino","44466","859-3822 Egestas. Rd.",111,10);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Fortune","H2I 5HZ","1829 Orci. Avenue",265,6);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Carson City","2677CW","2674 Ornare Av.",32,3);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Vandoeuvre-lÃ¨s-Nancy","61427","575-448 Egestas Avenue",163,2);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Forge-Philippe","MA00 5YM","Ap #385-7977 Fringilla Street",228,6);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Erpe","3452","7530 Elit St.",236,1);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Wyoming","65944","784-9769 Consectetuer Road",287,9);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Nocera Umbra","77225","Ap #368-4293 Sed Avenue",14,3);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Lakewood","5183","427-4911 Elit, St.",123,1);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Stuttgart","6200","Ap #592-8622 Sed, Rd.",125,3);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Vorselaar","77331","Ap #241-2874 Lectus Av.",130,3);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Calvello","8365","P.O. Box 402, 6884 Donec Rd.",277,10);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Frankfurt am Main","66340","3061 Morbi St.",78,3);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Hoeilaart","84530","3142 Dui, Avenue",285,4);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Tourinne","R98 2BG","P.O. Box 906, 9373 Eu Street",160,1);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Monstreux","U9N 3PC","P.O. Box 478, 6656 Sed Rd.",236,7);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("GÃ¼ssing","18769-550","136-2897 Nullam Street",22,6);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Wellingborough","08686","9583 A Ave",56,6);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Firozabad","61940-106","2176 Aliquam Av.",185,1);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Merchtem","5054","P.O. Box 394, 372 Auctor. Road",56,2);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Saint-LÃ´","214443","131-7451 Nascetur Av.",110,6);
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("NiterÃ³i","521767","166-8458 Aliquam St.",50,4);
