INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("49709","6389 Duis Rd.",1,1);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("50301","617-3604 Orci Av.",2,2);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("S5V 2X2","P.O. Box 859, 1424 Nostra, Rd.",3,3);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("743272","P.O. Box 603, 6692 Parturient Av.",4,4);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("2189","851-7556 Maecenas Av.",5,5);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("59028-104","P.O. Box 982, 8158 Egestas, Rd.",6,6);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("P2J 9T3","P.O. Box 186, 4625 Ultrices, Rd.",7,7);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("B62 6JF","7975 Dolor St.",8,8);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("7915","P.O. Box 702, 9273 Aliquam Avenue",9,9);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("5131","Ap #717-7318 Morbi St.",10,10);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("T9R 8C1","P.O. Box 938, 916 Mollis. Road",11,11);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Q2 8AP","4532 Risus. Ave",12,12);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("9010","Ap #493-1493 Sagittis St.",13,13);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("47268","P.O. Box 538, 8630 Pellentesque Rd.",14,14);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("321535","P.O. Box 697, 7216 Gravida Street",15,15);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("H2A 8P7","3371 Nec Av.",16,16);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("2058AV","638-4822 Nunc Av.",17,17);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("2291MA","611-6335 Lorem St.",18,18);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("6470","P.O. Box 353, 3191 Velit Road",19,19);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("31500","456-4828 Eget, Road",20,20);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("65952","110-9834 Neque Ave",21,21);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("65952","P.O. Box 621, 2599 Odio. Av.",22,22);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("50301","P.O. Box 747, 4859 Nam Av.",23,23);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("8756","P.O. Box 381, 6090 Cursus Rd.",24,24);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("P2J 9T3","478 Non, St.",25,25);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("4149","3449 Amet, Road",26,26);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("658380","704-2163 Arcu. Av.",27,27);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("7600ON","926-4919 Habitant Rd.",28,28);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("60713","Ap #719-3732 Ornare. St.",29,29);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("C8 9LM","P.O. Box 795, 6235 Etiam St.",30,30);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("409108","187-283 Pede, Rd.",31,31);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("8353","P.O. Box 232, 3449 Nec, Ave",32,32);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("6470","Ap #635-9152 Id, Av.",33,33);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("K4A 9H9","190-7110 Ultricies Rd.",34,34);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("426633","2194 Gravida. Ave",35,35);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("R8S 0T1","756-223 Tortor Ave",36,36);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("SZ1 1MN","629-1892 Mauris Rd.",37,37);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("B62 6JF","P.O. Box 214, 9130 Sem, Ave",38,38);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("51618","780-1252 Ipsum Av.",39,39);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("82701-962","954-232 Dolor. Road",40,40);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("47268","P.O. Box 347, 7880 Quis Street",41,41);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("P7R 9M7","859 Scelerisque St.",42,42);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("78822","P.O. Box 367, 921 Tortor St.",43,43);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("69742","P.O. Box 655, 4845 Nascetur St.",44,44);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("56394","P.O. Box 259, 4345 Pharetra. Road",45,45);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("94631","Ap #114-7787 Faucibus Av.",46,46);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("79227","P.O. Box 961, 2691 Eget, Road",47,47);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("8823MC","P.O. Box 143, 5700 Nulla Av.",48,48);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("7465","1609 Elit. St.",49,49);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("2476","3306 Dolor St.",50,50);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("5307","P.O. Box 356, 3617 Nam Rd.",51,51);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("40205","3988 Neque. Avenue",52,52);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("698417","Ap #541-8569 Duis St.",53,53);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("4200","Ap #224-4907 Mauris. Ave",54,54);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Y2X 7V0","2274 Et Av.",55,55);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("03072-851","P.O. Box 432, 9321 Praesent Rd.",56,56);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("10711","149-6025 Dolor St.",57,57);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("P7R 9M7","P.O. Box 427, 1884 Velit St.",58,58);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("69742","813-5586 Libero Rd.",59,59);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Q2 8AP","436-8127 Turpis St.",60,60);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("56394","Ap #382-6814 Vulputate, Ave",61,61);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("31500","951-2746 Non St.",62,62);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("25495","Ap #462-7475 Mauris. St.",63,63);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("7915","Ap #700-718 Quis Av.",64,64);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Q2 8AP","Ap #580-1695 Non, Rd.",65,65);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("65952","6602 Molestie Ave",66,66);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("98988","P.O. Box 214, 8677 Donec St.",67,67);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("56637","5867 Duis St.",68,68);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("4200","9018 Orci Av.",69,69);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("HC9H 1TM","Ap #472-5360 Orci. Rd.",70,70);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("9669CP","1202 Quisque Street",71,71);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("8327","9581 Aliquam St.",72,72);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("SZ1 1MN","P.O. Box 242, 1832 Suspendisse St.",73,73);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("T9R 8C1","Ap #822-3779 Posuere St.",74,74);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("6470","P.O. Box 378, 2060 Varius Street",75,75);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("1000FE","Ap #424-4227 Phasellus St.",76,76);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("K4A 9H9","632-3069 Quam Rd.",77,77);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("L1V 1T7","P.O. Box 252, 2793 Ligula Rd.",78,78);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("P2J 9T3","P.O. Box 386, 3832 Dapibus St.",79,79);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("8691DR","238-1026 Consectetuer Ave",80,80);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("60713","Ap #725-3881 Aenean Avenue",81,81);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("S5V 2X2","P.O. Box 737, 4483 Ut, Road",82,82);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("71329","626-8835 Dictum. Avenue",83,83);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("K4A 9H9","Ap #561-3129 Nisl Av.",84,84);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("5131","3869 At, Avenue",85,85);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("0078","8457 Dictum Street",86,86);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("808066","Ap #556-7919 Auctor Rd.",87,87);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("96206","3243 Mollis St.",88,88);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("T9R 8C1","429-4777 Sed Ave",89,89);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("129866","9557 Consequat Av.",90,90);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("3471","Ap #625-8899 A, Rd.",91,91);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("L1V 1T7","799-6251 Eu, Ave",92,92);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("321535","8238 Malesuada Avenue",93,93);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("9669CP","529-583 Lorem Rd.",94,94);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("8353","P.O. Box 148, 1942 Accumsan Rd.",95,95);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("53138","Ap #122-231 Velit Street",96,96);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("9717","455-7591 Enim Rd.",97,97);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("2291MA","631-7373 Nullam St.",98,98);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("HC9H 1TM","1440 At Rd.",99,99);
INSERT INTO `Addresses` (`address_place_zip`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("8327","208-7566 Sem St.",100,100);
