INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Driemasterstraat", "86", "4");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Korte Mate", "69", "64");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Kreekstraat", "9", "13");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Bonte Mantelstraat", "2", "80");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Weverbosdreef", "28", "36");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Alphonse Sifferdok", "60", "16");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Tortelduifstraat", "100", "48");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Achterstraat", "24", "9");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Jovastraat", "44", "30");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Winston Churchillplein", "9", "51");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Anjelierstraat", "17", "50");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Groenevalleilaan", "55", "28");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Ronselestraat", "85", "90");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Veldstraat", "62", "20");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Eversteinlaan", "24", "39");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Wondelgemstationplein", "48", "46");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Boesbeeklaan", "15", "68");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Opvoedingstraat", "44", "85");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Vijverhof", "29", "60");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Duddegemstraat", "94", "4");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Rietzangerstraat", "23", "18");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Ambassadeursweg", "11", "90");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Tichelrei", "69", "2");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Driebeekstraat", "77", "24");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Struifstraat", "51", "65");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Lammeken", "20", "55");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Paul Bergmansdreef", "99", "76");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Toekomststraat", "48", "89");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Campo-Santoplein", "57", "4");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Adelaarsstraat", "94", "98");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Henri Bernard de Tracylaan", "1", "73");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Luchterenhof", "69", "37");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Remi Vlerickstraat", "74", "38");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Spanjeveerstraat", "71", "62");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Kleinemoortelputstraat", "81", "66");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Pieter Hellebautstraat", "85", "76");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Adalwinstraat", "92", "17");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Kattenhoekstraat", "96", "45");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Winkelgate", "53", "99");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Nicolaas de Liemaeckereplein", "51", "4");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Heindriesstraat", "85", "73");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Venusschoentjestraat", "85", "100");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Dobbelslot", "10", "98");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Hondelee", "2", "93");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Laurent Delvauxstraat", "84", "94");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Kroonstraat", "18", "94");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Meerkoetlaan", "9", "94");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Priesterstraat", "4", "100");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Keizerpark", "32", "84");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Oude Akker", "2", "18");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Hagedoornlaan", "52", "6");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Lucie Dejardinpad", "97", "74");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Binnenweg", "91", "32");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Wessemweg", "88", "50");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Kramersplein", "18", "74");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Rietveld", "92", "99");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Arsenaalstraat", "92", "9");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Gaverlandstraat", "65", "1");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Kreeftstraat", "52", "97");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Achilles Heyndrickxlaan", "78", "65");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Noormanstraat", "88", "80");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Stroomkenskerkweg", "21", "61");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Dagmaalhof", "23", "74");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Kuipgat", "82", "64");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Marathonstraat", "43", "85");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Merendreesesteenweg", "40", "41");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Sint-Clarastraat", "80", "91");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Schepenhuisstraat", "44", "32");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Biermannekenspad", "50", "81");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Baaisteeg", "69", "42");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Frans Ackermanstraat", "42", "78");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Vrijdagmarkt", "53", "37");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Virginiastraat", "41", "81");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Jozef Horenbantweg", "22", "96");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Venusstraat", "93", "88");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Kauwplein", "86", "77");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Veurestraat", "62", "65");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Vogelmarkt", "47", "70");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Hoefijzerstraat", "79", "48");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Watergraafstraat", "29", "76");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Bijlokehof", "50", "23");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Mai Zetterlingstraat", "82", "41");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Potuitstraat", "22", "36");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Ezelstraatje", "23", "97");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Bomastraat", "40", "59");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Muidepoort", "70", "90");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Oostdonkstraat", "9", "6");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Kleindokkaai", "89", "47");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Handelsdok", "45", "30");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Stijn Streuvelslaan", "79", "62");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Bloemstraat", "4", "58");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Slindonk", "43", "87");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Victor Frisstraat", "93", "48");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Lindemeers", "25", "44");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Zestiengemeten", "92", "32");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Emiel Lossystraat", "41", "73");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Rodelijvekensstraat", "64", "32");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Godelieve Joliestraat", "47", "16");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Stoppelstraat", "84", "11");
INSERT INTO `Addresses` (`address_city`,`address_zipcode`,`address_street`,`address_street_number`,`address_street_bus`) VALUES ("Gent", "9000", "Alfred Vanderstegenlaan", "40", "46");