CREATE TABLE `users` (
	`ID` INT(11) NOT NULL AUTO_INCREMENT,
	`email` VARCHAR(64) NOT NULL DEFAULT '0',
	`password` CHAR(64) NOT NULL DEFAULT '0',
	`firstname` VARCHAR(64) NOT NULL DEFAULT '0',
	`lastname` VARCHAR(64) NULL DEFAULT '0',
	`role` ENUM('USER','ADMIN') NOT NULL DEFAULT 'USER',
	PRIMARY KEY (`ID`),
	UNIQUE INDEX `email` (`email`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB;